### ISSUE TITLE
Documentation on setup required to run GraalJS

### ISSUE THREAD

**Issue by Hoff97** [graalvm/graal-js-jdk11-maven-demo#31]
I am trying to replace nashorn by GraalJS in a big Java application. Thus I can not start from this repository. Since I could not find information in the graal docs, I am asking this here:
- Which command line arguments have to be set so the graal compiler is used (-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI --module-path=... --upgrade-module-path=... right?)
- Which jars should be located in the folder for the  --module-path argument?
- Do I only have to set these arguments on execution or also on compilation?

**Comment by boris-spas** [comment]
Safest thing to do is run maven in verbose mode (-X) and see exactly what it does (e.g.  `mvn -X exec:exec). 
I don't think there shouldn't be any compile time changes needed.

**Comment by wirthi** [comment]
Hi @Hoff97,

We have this repo instead of a textual (and fast outdating) documentation. Even when you don't start from this repo, it should be able to serve as starting point what you need to do in your own application.

The commandline you can read from https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/2d6a8dac8910c095ec4a00cc566e1b73e5a62718/pom.xml#L56 and the dependencies from the block following https://github.com/graalvm/graal-js-jdk11-maven-demo/blob/2d6a8dac8910c095ec4a00cc566e1b73e5a62718/pom.xml#L20

Regarding runtime/compilation: that depends on what exactly you do in your application. In our applications, we would typically create a `org.graalvm.polyglot.Context` object, so the dependency to at least `org.graalvm.sdk` will be relevant even at compile time. 

Best,
Christian
